import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, updateDoc, deleteDoc, collection, getDocs, onSnapshot, query, where, writeBatch } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
const $=id=>document.getElementById(id), C=window.PIANOCASA_CONFIG||{};
const badConfig=!C.firebase||String(C.firebase.apiKey||'').startsWith('INCOLLA_');
let app,auth,db,user,userDoc,householdId,member,profiles={},days=[],extras=[],checks={},currentProfileId,currentDate=isoToday(),listeners=[],hideDone=false;
if(badConfig){$('setupView').classList.remove('hidden')}else{app=initializeApp(C.firebase);auth=getAuth(app);db=getFirestore(app);$('authView').classList.remove('hidden');onAuthStateChanged(auth,handleAuth)}
function isoToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseISO(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function addDays(s,n){const d=parseISO(s);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmt(s,short=false){if(!s)return'';return new Intl.DateTimeFormat('it-IT',short?{weekday:'short',day:'2-digit',month:'2-digit'}:{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(parseISO(s))}
function datesBetween(a,b){let r=[];if(!a||!b||a>b)return r;for(let d=a;d<=b&&r.length<400;d=addDays(d,1))r.push(d);return r}
function idSafe(s){return btoa(unescape(encodeURIComponent(s))).replaceAll('/','_').replaceAll('+','-').replaceAll('=','')}
function allCats(p){return p.meals.flatMap(m=>m.categories)}
function itemMap(p){const m={};for(const meal of p.meals)for(const c of meal.categories)for(const it of c.items)m[it.id]=it;return m}
function dayDoc(pid,date){return days.find(x=>x.profileId===pid&&x.date===date)||{profileId:pid,date,selections:{},consumed:{}}}
function selectedItem(p,d,c){const id=d.selections?.[c.id];return id?c.items.find(x=>x.id===id):null}
function totalKcal(p,d){let t=0;for(const c of allCats(p)){const i=selectedItem(p,d,c);if(i)t+=i.kcal}return t}
function complete(p,d){return allCats(p).every(c=>selectedItem(p,d,c))}
function show(id){['authView','onboardView','appView'].forEach(x=>$(x).classList.toggle('hidden',x!==id));$('signoutBtn').classList.toggle('hidden',id!=='appView')}
$('loginBtn')?.addEventListener('click',async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('authMsg').textContent=''}catch(e){$('authMsg').textContent=e.message}})
$('registerBtn')?.addEventListener('click',async()=>{try{await createUserWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('authMsg').textContent=''}catch(e){$('authMsg').textContent=e.message}})
$('signoutBtn').onclick=()=>signOut(auth);
async function handleAuth(u){clearListeners();user=u;if(!u){show('authView');return}const snap=await getDoc(doc(db,'users',u.uid));if(!snap.exists()){show('onboardView');renderOnboard()}else{userDoc=snap.data();householdId=userDoc.householdId;currentProfileId=userDoc.profileId;await startApp()}}
function clearListeners(){listeners.forEach(f=>f());listeners=[]}
function renderOnboard(){show('onboardView');$('onboardBody').innerHTML=`<p>Scegli solo la prima volta.</p><div class="actions"><button id="createHome" class="primary">Sono Vincenzo · crea famiglia</button></div><hr><label>Codice invito<input id="inviteCode" maxlength="14" placeholder="codice da Vincenzo"></label><button id="joinHome" class="primary" style="margin-top:8px">Sono Anna · entra</button><div id="onMsg" class="msg"></div>`;$('createHome').onclick=createHousehold;$('joinHome').onclick=joinHousehold}
async function createHousehold(){try{const hid=crypto.randomUUID();const b=writeBatch(db);b.set(doc(db,'households',hid),{createdAt:Date.now(),label:'Casa'});b.set(doc(db,'households',hid,'members',user.uid),{uid:user.uid,email:user.email,profileId:'vincenzo',displayName:'Vincenzo',notifyAt:'07:30',includePartnerMenu:false,owner:true});b.set(doc(db,'users',user.uid),{householdId:hid,profileId:'vincenzo',email:user.email});await b.commit();location.reload()}catch(e){$('onMsg').textContent=e.message}}
async function joinHousehold(){try{const code=$('inviteCode').value.trim().toUpperCase();const invRef=doc(db,'invites',code),s=await getDoc(invRef);if(!s.exists())throw new Error('Codice non trovato.');const inv=s.data();if(inv.claimedBy)throw new Error('Codice già usato.');await updateDoc(invRef,{claimedBy:user.uid,claimedAt:Date.now()});const b=writeBatch(db);b.set(doc(db,'households',inv.householdId,'members',user.uid),{uid:user.uid,email:user.email,profileId:inv.profileId,displayName:inv.displayName,notifyAt:'07:30',includePartnerMenu:true,owner:false,inviteCode:code});b.set(doc(db,'users',user.uid),{householdId:inv.householdId,profileId:inv.profileId,email:user.email});await b.commit();location.reload()}catch(e){$('onMsg').textContent=e.message}}
async function startApp(){show('appView');const ms=await getDoc(doc(db,'households',householdId,'members',user.uid));member=ms.data();currentProfileId=currentProfileId||member.profileId;listeners.push(onSnapshot(collection(db,'households',householdId,'profiles'),s=>{profiles={};s.forEach(x=>profiles[x.id]=x.data());renderAll()}));listeners.push(onSnapshot(collection(db,'households',householdId,'days'),s=>{days=s.docs.map(x=>({id:x.id,...x.data()}));renderAll()}));listeners.push(onSnapshot(collection(db,'households',householdId,'extras'),s=>{extras=s.docs.map(x=>({id:x.id,...x.data()}));renderShopping()}));listeners.push(onSnapshot(collection(db,'households',householdId,'checks'),s=>{checks={};s.forEach(x=>checks[x.id]=x.data());renderShopping()}));renderMember();}
function renderAll(){if(!profiles[currentProfileId]&&profiles[member?.profileId])currentProfileId=member.profileId;renderProfileSelect();renderToday();renderCalendar();renderShopping();renderRules()}
function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='shopping')renderShopping()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function renderProfileSelect(){const s=$('profileSelect');if(!s)return;s.innerHTML='';Object.values(profiles).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.displayName;o.selected=p.id===currentProfileId;s.appendChild(o)});s.onchange=()=>{currentProfileId=s.value;const p=profiles[currentProfileId];currentDate=p.startDate||isoToday();renderAll()}}
async function saveDay(pid,date,d){const p=profiles[pid];d.summary=buildSummary(p,d);d.kcal=totalKcal(p,d);d.updatedAt=Date.now();await setDoc(doc(db,'households',householdId,'days',`${pid}_${date}`),d,{merge:true})}
function buildSummary(p,d){const out={};for(const meal of p.meals){let arr=[];for(const c of meal.categories){const it=selectedItem(p,d,c);if(it)arr.push(`${it.name}${it.grams!=null?' '+it.grams+' g':''}`)}out[meal.id]=arr.join(' + ')}return out}
function mealTotal(p,d,m){let t=0;for(const c of m.categories){const i=selectedItem(p,d,c);if(i)t+=i.kcal}return t}
function renderToday(){const p=profiles[currentProfileId];if(!p)return;const d=dayDoc(p.id,currentDate);$('todayTitle').textContent=fmt(currentDate);$('profileLabel').textContent=p.displayName;$('kcalTotal').textContent=totalKcal(p,d);$('kcalBar').style.width=Math.min(100,totalKcal(p,d)/p.targetKcal*100)+'%';const ks=$('kcalState');ks.className='pill';if(!complete(p,d))ks.textContent='da completare';else if(totalKcal(p,d)>=p.kcalLow&&totalKcal(p,d)<=p.kcalHigh){ks.textContent='centrato';ks.classList.add('good')}else{ks.textContent=totalKcal(p,d)>p.kcalHigh?'alto':'basso';ks.classList.add('warn')};$('freqInfo').innerHTML=minimumInfo(p,currentDate);$('meals').innerHTML='';for(const meal of p.meals){const sec=document.createElement('section');sec.className='meal';sec.innerHTML=`<div class="mealhead"><h2>${meal.label}</h2><div><b>${mealTotal(p,d,meal)} kcal</b></div></div>`;for(const c of meal.categories){const box=document.createElement('div');box.className='cat';box.innerHTML=`<h3>${c.label}</h3><div class="options"></div>`;const opts=box.querySelector('.options');for(const it of c.items){const b=document.createElement('button');b.className='opt';const sel=d.selections?.[c.id]===it.id;if(sel)b.classList.add('selected');const block=blockedReason(p,currentDate,c.id,it.id,d);b.disabled=!sel&&!!block;b.innerHTML=`${it.name}${it.grams!=null?' — '+it.grams+' g':''}<small>${it.kcal} kcal</small>${block&&!sel?`<span class="limit">${block}</span>`:''}`;b.onclick=async()=>{const nd=structuredClone(dayDoc(p.id,currentDate));nd.selections||={};if(sel)delete nd.selections[c.id];else nd.selections[c.id]=it.id;await saveDay(p.id,currentDate,nd)};opts.appendChild(b)}box.appendChild(opts);sec.appendChild(box)}$('meals').appendChild(sec)}}
function selectedOccurrences(p,tag,excludeDate=null,excludeCat=null){const im=itemMap(p), arr=[];for(const d of days.filter(x=>x.profileId===p.id)){for(const [cat,id] of Object.entries(d.selections||{})){if(d.date===excludeDate&&cat===excludeCat)continue;const it=im[id];if(it?.tags?.includes(tag))arr.push(d.date)}}return arr}
function violatesRolling(existing,candidate,maxCount,windowDays){const a=[...existing,candidate].sort();for(let i=0;i<a.length;i++){let c=0;const start=parseISO(a[i]);for(let j=i;j<a.length;j++){const diff=(parseISO(a[j])-start)/86400000;if(diff<=windowDays-1)c++;else break}if(c>maxCount)return true}return false}
function blockedReason(p,date,catId,itemId,d){const it=itemMap(p)[itemId];if(!it)return'';for(const r of p.rules||[]){if(r.disabledWhen&&p.conditions?.[r.disabledWhen]&&it.tags?.includes(r.tag))return r.label+' non disponibile';if(r.maxCount&&it.tags?.includes(r.tag)){const occ=selectedOccurrences(p,r.tag,date,catId);if(violatesRolling(occ,date,r.maxCount,r.days||7))return `limite ${r.maxCount} ogni ${r.days||7} giorni`}}return''}
function minimumInfo(p,date){let txt=[];for(const r of p.minimums||[]){const from=addDays(date,-6),to=date;const im=itemMap(p);let n=0;for(const d of days.filter(x=>x.profileId===p.id&&x.date>=from&&x.date<=to))for(const id of Object.values(d.selections||{}))if(im[id]?.tags?.includes(r.tag))n++;txt.push(`${r.label}: ${n}/${r.minCount} minimo negli ultimi 7 giorni`)}return txt.join(' · ')}
$('prevDay').onclick=()=>{currentDate=addDays(currentDate,-1);renderToday()};$('nextDay').onclick=()=>{currentDate=addDays(currentDate,1);renderToday()};$('copyPrev').onclick=async()=>{const p=profiles[currentProfileId],src=dayDoc(p.id,addDays(currentDate,-1));const nd={profileId:p.id,date:currentDate,selections:structuredClone(src.selections||{}),consumed:{}};await saveDay(p.id,currentDate,nd)};$('clearDay').onclick=async()=>{if(confirm('Azzero questo giorno?'))await deleteDoc(doc(db,'households',householdId,'days',`${currentProfileId}_${currentDate}`))};
function renderCalendar(){const p=profiles[currentProfileId];if(!p)return;$('startDate').value=p.startDate||'';$('endDate').value=p.endDate||'';const box=$('calendarDays');box.innerHTML='';for(const date of datesBetween(p.startDate,p.endDate)){const d=dayDoc(p.id,date),row=document.createElement('div');row.className='dayrow';row.innerHTML=`<button><b>${fmt(date)}</b><div class="muted">${complete(p,d)?totalKcal(p,d)+' kcal':Object.keys(d.selections||{}).length+' scelte'}</div></button><span class="pill ${complete(p,d)?'good':''}">${complete(p,d)?'completo':'da fare'}</span>`;row.querySelector('button').onclick=()=>{currentDate=date;tab('today');renderToday()};box.appendChild(row)}}
$('savePeriod').onclick=async()=>{const p=profiles[currentProfileId],s=$('startDate').value,e=$('endDate').value;if(!s||!e||s>e){alert('Controlla le date');return}await updateDoc(doc(db,'households',householdId,'profiles',p.id),{startDate:s,endDate:e});currentDate=s};
function collectShop(){const map=new Map();for(const p of Object.values(profiles)){const im=itemMap(p);for(const d of days.filter(x=>x.profileId===p.id&&(!p.startDate||x.date>=p.startDate)&&(!p.endDate||x.date<=p.endDate))){for(const id of Object.values(d.selections||{})){const it=im[id];if(!it)continue;const key=it.name.toLowerCase();if(!map.has(key))map.set(key,{key,name:it.name,grams:0,count:0,department:it.department,extra:false});const x=map.get(key);x.count++;if(it.grams!=null)x.grams+=it.grams}}for(const sp of p.supplements||[]){if(!p.startDate||!p.endDate)continue;const nd=datesBetween(p.startDate,p.endDate).length,key=sp.name.toLowerCase();if(!map.has(key))map.set(key,{key,name:sp.name,count:0,grams:null,department:sp.department||'Integratori',extra:false,unit:sp.unit});const x=map.get(key);x.count+=(sp.qtyPerDay||0)*nd}}return [...map.values()]}
function qty(x){if(x.extra)return `${x.qty||''} ${x.unit||''}`.trim();if(x.grams!=null&&x.grams>0)return x.grams>=1000?`${(x.grams/1000).toLocaleString('it-IT',{maximumFractionDigits:2})} kg`:`${x.grams} g`;return `${x.count} ${x.unit||'porzioni'}`}
function renderShopping(){if(!householdId)return;let arr=collectShop().concat(extras.map(e=>({...e,key:'extra:'+e.id,extra:true})));const sort=$('shopSort')?.value||'dept';arr.sort((a,b)=>sort==='alpha'?a.name.localeCompare(b.name,'it'):(a.department||'Altro').localeCompare(b.department||'Altro','it')||a.name.localeCompare(b.name,'it'));const box=$('shoppingList');if(!box)return;box.innerHTML='';let last='';for(const x of arr){const cid=idSafe(x.key),done=!!checks[cid]?.checked;if(hideDone&&done)continue;if(sort==='dept'&&(x.department||'Altro')!==last){last=x.department||'Altro';const h=document.createElement('div');h.className='dept';h.textContent=last;box.appendChild(h)}const r=document.createElement('div');r.className='shoprow'+(done?' checked':'');r.innerHTML=`<input type="checkbox" ${done?'checked':''}><div><b>${x.name}</b>${x.extra?'<span class="extraBadge">EXTRA</span>':''}<div class="muted">${x.department||'Altro'}</div></div><div style="text-align:right"><b>${qty(x)}</b>${x.extra?'<div><button class="danger deleteExtra" style="margin-top:6px;padding:5px 8px;font-size:11px">Elimina</button></div>':''}</div>`;r.querySelector('input').onchange=async e=>setDoc(doc(db,'households',householdId,'checks',cid),{checked:e.target.checked,key:x.key,updatedAt:Date.now()});if(x.extra){r.querySelector('.deleteExtra').onclick=async()=>{if(!confirm(`Eliminare "${x.name}" dagli EXTRA?`))return;await deleteDoc(doc(db,'households',householdId,'extras',x.id));try{await deleteDoc(doc(db,'households',householdId,'checks',cid))}catch{}}}box.appendChild(r)}$('shopInfo').textContent=`${arr.length} voci · somma dei due profili`}
$('shopSort').onchange=renderShopping;$('hideChecked').onclick=()=>{hideDone=!hideDone;$('hideChecked').textContent='Nascondi presi: '+(hideDone?'SÌ':'NO');renderShopping()};$('addExtra').onclick=()=>$('modal').classList.remove('hidden');$('cancelExtra').onclick=()=>$('modal').classList.add('hidden');$('saveExtra').onclick=async()=>{const name=$('extraName').value.trim();if(!name)return;const ref=doc(collection(db,'households',householdId,'extras'));await setDoc(ref,{name,qty:Number($('extraQty').value||1),unit:$('extraUnit').value.trim()||'pz',department:$('extraDept').value,createdAt:Date.now()});$('modal').classList.add('hidden');$('extraName').value=''};$('shareShop').onclick=async()=>{const arr=collectShop().concat(extras.map(e=>({...e,key:'extra:'+e.id,extra:true})));const text=['LISTA DELLA SPESA','',...arr.map(x=>`• ${x.name}: ${qty(x)}${x.extra?' [EXTRA]':''}`)].join('\n');if(navigator.share)try{await navigator.share({title:'Spesa PianoCasa',text})}catch{}else{await navigator.clipboard.writeText(text);alert('Lista copiata')}};
async function renderMember(){const s=await getDoc(doc(db,'households',householdId,'members',user.uid));member=s.data();$('memberInfo').innerHTML=`<b>${member.displayName}</b><div class="muted">${user.email}</div>`;$('notifyAt').value=member.notifyAt||'07:30';$('includePartner').checked=!!member.includePartnerMenu;renderInvite()}
$('saveNotify').onclick=async()=>{await updateDoc(doc(db,'households',householdId,'members',user.uid),{notifyAt:$('notifyAt').value,includePartnerMenu:$('includePartner').checked});$('pushMsg').textContent='Impostazioni salvate.';renderMember()};
async function renderInvite(){const area=$('inviteArea');if(!member?.owner){area.innerHTML='<div class="muted">Sei collegata alla famiglia.</div>';return}const qs=await getDocs(query(collection(db,'invites'),where('householdId','==',householdId),where('profileId','==','anna')));let active=qs.docs.find(x=>!x.data().claimedBy);if(active){area.innerHTML=`Codice per Anna: <b>${active.id}</b>`;return}area.innerHTML='<button id="makeInvite">Genera codice per Anna</button>';$('makeInvite').onclick=async()=>{const code=Math.random().toString(36).slice(2,10).toUpperCase();await setDoc(doc(db,'invites',code),{householdId,profileId:'anna',displayName:'Anna',createdBy:user.uid,createdAt:Date.now(),claimedBy:null});renderInvite()}}
$('enablePush').onclick=async()=>{try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Push non supportato. Su iPhone installa prima l’app nella schermata Home.');const reg=await navigator.serviceWorker.register('./sw.js');const perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('Permesso notifiche non concesso.');const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlB64(C.vapidPublicKey)});const j=sub.toJSON(),id=idSafe(user.uid+'_'+j.endpoint);await setDoc(doc(db,'households',householdId,'pushSubscriptions',id),{uid:user.uid,profileId:member.profileId,endpoint:j.endpoint,keys:j.keys,createdAt:Date.now()});$('pushMsg').textContent='Notifiche attive su questo iPhone.'}catch(e){$('pushMsg').textContent=e.message}}
function urlB64(s){const pad='='.repeat((4-s.length%4)%4),b64=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
$('importSeed').onclick=async()=>{try{const f=$('seedFile').files[0];if(!f)throw new Error('Seleziona il file JSON privato.');const seed=JSON.parse(await f.text());const b=writeBatch(db);for(const p of seed.profiles)b.set(doc(db,'households',householdId,'profiles',p.id),{...p,startDate:p.startDate||isoToday(),endDate:p.endDate||addDays(isoToday(),13)});await b.commit();$('seedMsg').textContent='Diete importate nel cloud privato.'}catch(e){$('seedMsg').textContent=e.message}}
function renderRules(){const p=profiles[currentProfileId],box=$('rulesList');if(!p||!box)return;box.innerHTML='';for(const r of p.rules||[]){const d=document.createElement('div');d.className='rule';d.innerHTML=`<b>${r.label}</b><span class="muted">${r.disabledWhen?'bloccato quando '+r.disabledWhen:`massimo ${r.maxCount} ogni ${r.days} giorni`} · ${r.source||''}</span>`;box.appendChild(d)}for(const mn of p.minimums||[]){const d=document.createElement('div');d.className='rule';d.innerHTML=`<b>${mn.label}</b><span class="muted">obiettivo ${mn.minCount}${mn.targetMax?'–'+mn.targetMax:''} ogni ${mn.days} giorni</span>`;box.appendChild(d)}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
