const $=id=>document.getElementById(id),snapshot=PCOffline.read('pc19_snapshot',null);let hide=false;
function el(tag,text){const n=document.createElement(tag);if(text!=null)n.textContent=text;return n}
function save(x,kind,id,data){PCOffline.queue(snapshot.uid,snapshot.hid,kind,id,{...data,updatedAt:Date.now()});PCOffline.write('pc19_snapshot',snapshot)}
if(snapshot){for(const q of PCOffline.pending().filter(q=>q.uid===snapshot.uid&&q.hid===snapshot.hid)){for(const x of snapshot.items){if(q.kind==='checks'&&q.id===x.checkId&&q.data.basis===x.basis)x.checked=q.data.checked;if(q.kind==='storeMappings'&&q.id===snapshot.mappingIds[x.key])x.aisle=q.data.aisle;if(q.kind==='shopAdjustments'&&q.id===x.checkId&&q.data.basis===x.basis)x.quantity=q.data.amount+' '+q.data.unit}}}
function render(){
 $('list').replaceChildren();if(!snapshot){$('status').textContent='Nessuna lista salvata. Apri la sezione Spesa con internet prima di uscire.';return}
 $('status').textContent=`${snapshot.range.from} → ${snapshot.range.to} · copia del ${new Date(snapshot.at).toLocaleString('it-IT')} · ${PCOffline.pending().length} modifiche locali`;
 const a=snapshot.aisles,rank=Object.fromEntries(a.map((x,i)=>[x[0],i]));
 for(const x of [...snapshot.items].filter(x=>(!hide||!x.checked)&&x.name.toLocaleLowerCase().includes($('search').value.toLocaleLowerCase())).sort((x,y)=>($('order').value==='aisle'?(rank[x.aisle]??999)-(rank[y.aisle]??999):0)||x.name.localeCompare(y.name,'it'))){
 const row=el('div');row.className='card';const label=el('label'),c=el('input');c.type='checkbox';c.checked=x.checked;label.append(c,document.createTextNode(' '+x.name+' — '+x.quantity));row.append(label,el('p',x.servings),el('p',x.pieces));
 c.onchange=()=>{try{save(x,'checks',x.checkId,{checked:c.checked,key:x.key,periodId:snapshot.range.periodId,rangeFrom:snapshot.range.from,rangeTo:snapshot.range.to,basis:x.basis});x.checked=c.checked;PCOffline.write('pc19_snapshot',snapshot);render()}catch(e){alert('Non salvato: '+e.message);c.checked=x.checked}};
 const quantity=el('button','Modifica quantità');quantity.onclick=()=>{const amount=prompt('Quantità da acquistare',x.amount??'');if(amount===null)return;const unit=prompt('Unità: g, kg, ml, L, pz o confezioni',x.unit||'g');if(unit===null)return;try{const n=PCCore.number(amount);if(n<0||!unit.trim())throw Error('Quantità non valida');save(x,'shopAdjustments',x.checkId,{amount:n,unit:unit.trim(),basis:x.basis,key:x.key,periodId:snapshot.range.periodId,rangeFrom:snapshot.range.from,rangeTo:snapshot.range.to});x.amount=n;x.unit=unit.trim();x.quantity=n+' '+unit.trim();x.pieces='Quantità corretta: verifica il peso / numero in negozio';snapshot.offers=null;PCOffline.write('pc19_snapshot',snapshot);render()}catch(e){alert(e.message)}};row.append(quantity);
 const select=el('select');select.append(new Option('Reparto da assegnare',''));a.forEach(([id,name])=>select.append(new Option(id+' · '+name,id)));select.value=x.aisle||'';
 select.onchange=()=>{try{save(x,'storeMappings',snapshot.mappingIds[x.key],{storeId:'iper-tosano-pradamano',name:x.name,aisle:select.value||null});x.aisle=select.value;PCOffline.write('pc19_snapshot',snapshot);render()}catch(e){alert(e.message)}};
 if(snapshot.offers){const f=snapshot.offers,prices=f.items.find(p=>p.key===x.key),key=f.storeIndex+'|'+x.key,b=prices?.base,o=prices?.offer;let chosen=!!f.choices.values[key];const eligible=PCCore.offerBetter(b,o)&&o.confirmed&&PCCore.priceValid(o,f.date);const display=()=>{const p=chosen&&eligible?o:b;return p?`${f.store} · ${p.product} · ${p.packages} confezioni · € ${(p.totalCents/100).toFixed(2)} · valido ${p.validUntil}`:'Prezzo non trovato'};const price=el('p',display());row.append(price);if(eligible){const offer=el('button',chosen?'Torna alla scelta base':`Offerta: ${o.packages} confezioni · € ${(o.totalCents/100).toFixed(2)}`);offer.onclick=()=>{try{chosen=!chosen;f.choices.values[key]=chosen;save(x,'savings',f.choiceId,{type:'choices',values:f.choices.values,storeIndex:f.storeIndex});render()}catch(e){alert(e.message)}};row.append(offer)}}
 row.append(el('label','Correggi reparto Tosano'),select);$('list').append(row);
 }
}
$('search').oninput=render;$('order').onchange=render;$('hide').onclick=()=>{hide=!hide;$('hide').textContent=hide?'Mostra anche presi':'Nascondi presi';render()};render();
